GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/647698b47615866fc9f71884
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "teste-number-regexlast",
    "number": "09-1234556"
}
###
GET http://localhost:3001/info
###
DELETE http://localhost:3001/api/persons/6477a82951490cd430b9b214
###
PUT http://localhost:3001/api/persons/64768f2f20c7ab9d538fa9a7

{
    "name": "MuRillo A",
    "number": "8989asasas898"
}