GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "This",
    "number": "(415) 321-4021"
}
###
GET http://localhost:3001/info